# Generated by Django 6.1.1 on 2026-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="quantity_views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ведется подсчет количество просмотров объекта",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
