# Generated by Django 6.1.1 on 2026-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_quantity_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте факт опубликования статьи.",
                verbose_name="Опубликовано",
            ),
        ),
    ]
